name: Deploy IaC for SDN Web Streaming

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: MyWebDeploy
    steps:
    - name: Checkout
      uses: actions/checkout@v2

      # Configure AWS Credential
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY_ID }} 
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: us-east-1
      # Deploy to AWS CloudFormation
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1 
      with:
        name: Test-Pipeline-IaC
        template: Test-Web-Deploy.yaml 
        no-fail-on-empty-changeset: "1"
        parameter-overrides: EnvironmentName=${{ env.ENV_NAME }}
